# Generated by Django 3.2.8 on 2021-11-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_car',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='my_car',
            name='roll_no',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
