# Generated by Django 2.2.12 on 2021-11-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211102_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_car',
            old_name='roll_no',
            new_name='player_ID',
        ),
    ]
